development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: www_nihongo-chushin_com_development

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: www_nihongo-chushin_com_staging

staging_heroku:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: www_nihongo-chushin_com_staging_heroku

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: www_nihongo-chushin_com_production
