postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:

mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:


default: &default
  <<: *postgresql
  # <<: *mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  timeout: 5000

development:
  <<: *default
  database: www_nihongo_chushin_com_development

test:
  <<: *default
  database: www_nihongo_chushin_com_test
